### ISSUE TITLE
Not working in Eclipse 2020-06

### ISSUE THREAD

**Issue by mheydem** [eclipse-cbi/targetplatform-dsl#113]
After installing in Eclipse 2020-06 via "Install new Software" using the update-site http://download.eclipse.org/cbi/tpd/3.0.0-SNAPSHOT the expected context menu entries for tpd files are missing. Additionally some PDE features are missing: Target Platform in Preferences and Eclipse Application launch configurations. Unfortunately uninstalling the tpd stuff from eclipse does not recover the PDE features.

**Comment by mbarbero** [comment]
Thanks for the report. I don't have time currently to dig into the issue. Would you be willing to investigate? I could provide assistance.

**Comment by frankbenoit** [comment]
This might be due to Guice 5 being installed, bringing Guava 30 as well.
After enforcing Guice 3, it works for me.

**Comment by mheydem** [comment]
It is working in Eclipse 2021-12.
I guess this won't be fixed.

**Comment by akurtakov** [comment]
This functionality is clearly looking for new maintainer. There are already multiple ways to declare target platforms and with latest enhancements to be able to refer to Maven artifacts directly this one is becoming even more outdated. If no one steps up to take over there are multiple paths forward - plain PDE target files, M2E extension to use Maven artifacts in the target file and (Oomph targlets)[https://wiki.eclipse.org/Oomph_Targlets]. All these are well maintained.

**Comment by merks** [comment]
This *.tdp stuff is quite widely used because it's really very nice.  See this recent forum thread about Targlets and *.tdp:

https://www.eclipse.org/forums/index.php/mv/msg/1101039/1854375/#msg_1854375

One reason why *.tdp is so popular is because the PDE editor is, how to say it nicely, kind of horrible.  I thought about how to fix that, but the problem is that the PDE design is focused on downloading all the plugins and features in order to provide information about them in the editor.  So the editing experience isn't just based on using p2 metadata from the repositories while editing, as is the case for *.tdp and Oomph's targlets.  I.e., org.eclipse.pde.core.target.ITargetLocation.getBundles() which provides org.eclipse.pde.core.target.TargetBundle.getBundleInfo() where the only implementation is org.eclipse.equinox.internal.p2.publisher.eclipse.GeneratorBundleInfo so it just relies on published info from bundle and feature artifacts.  Maybe where are ways to improve this in PDE, but right now, in general, you open the PDE editor and it starts to download everything, which takes long, might not be successful, and fills up the disk; it is simply not an ideal experience...

But yes, your point *.tdp needing maintainers is a good one.  Far too many people assume that all these technologies are just a free ride and somehow must learn the painful way when it stops working that they personally need to do something to keep it working...
