### ISSUE TITLE
Wrong link target behind nightly update site link

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cbi/targetplatform-dsl#133]
https://download.eclipse.org/cbi/updates/tpd/nightly/latest/ says to copy the link target of the contained update site link, e.g. from the upper link in this image:
![grafik](https://user-images.githubusercontent.com/406876/236623553-88570571-caeb-40b9-bec7-c9b92f81a980.png)

However, while the link _text_ is correct, the link target is not. It points to https://download.eclipse.org/justj?file=cbi/updates/tpd/nightly/latest

**Comment by merks** [comment]
It says to press the pencil glyph. The link gives a raw view of the file system of the server.

**Comment by Bananeweizen** [comment]
Re-reading, that seems right. In that case the bug is only that it didn't fit my expectation (and I would assume, also not that of many other people). I've never seen a URL as text pointing to another URL in the link (except for scam and spam).
Not sure how to continue with the issue then. Feel free to close...

**Comment by merks** [comment]
I looked at the template and it adds an actual href only if the regular link points to https://download.eclipse.org.  Otherwise there is no link because it would be a self link, just the pencil icon. 

But I could change JustJ's repository publisher put the link on a 🧰 glyph:

https://www.compart.com/en/unicode/U+1F9F0

So that there is no point of confusion...

**Comment by Bananeweizen** [comment]
Sounds okay to me.

**Comment by merks** [comment]
It looks like this now:

![image](https://user-images.githubusercontent.com/208716/236631737-24100c70-47b3-4341-b65d-0533077e2409.png)

So no misleading link that one might inadvertently copy...
