### ISSUE TITLE
Source formatting broken with 3.0.0-SNAPSHOT / Eclipse 2018-12

### ISSUE THREAD

**Issue by pcdavid** [eclipse-cbi/targetplatform-dsl#84]
Versions:
- target-platform-dsl 3.0.0-SNAPSHOT (3.0.0.201809052136)
- Eclipse 2018-12
- Xtext 2.16.0.v20181203-1555

When trying to format a `.targetplatform` file, all the content ends up on a single huge line.

**Comment by miklossy** [comment]
Since the migration to the new mwe2 workflow the currently implemented [formatter](https://github.com/eclipse-cbi/targetplatform-dsl/blob/master/org.eclipse.cbi.targetplatform/src/main/java/org/eclipse/cbi/targetplatform/formatting/TargetPlatformFormatter.xtend) is not properly bound any more.

The solution would be to provide a formatter implementation based on the new Xtext Formatter API. See also [comment](https://github.com/eclipse-cbi/targetplatform-dsl/issues/48#issuecomment-152463183).

**Comment by miklossy** [comment]
I created a [PR](https://github.com/eclipse-cbi/targetplatform-dsl/pull/100) to replace Xtext formatter by Xtext formatter2.

**Comment by miklossy** [comment]
@mbarbero This issue is also fixed by PR #100 and can be closed.

**Comment by mbarbero** [comment]
Closing. Thanks @miklossy
